### ISSUE TITLE
 Kernel unexpectedly dying; line of code: viz_cnmf.show

### ISSUE THREAD

**Issue by CharlotteWenxin** [nel-lab/mesmerize-core#307] opened 2024-06-28 19:26 UTC
computer: window 11, 32GB RAM (15.6GB usable) processor: AMD Ryzen 7 7800X3D 8-Core Processor 

I couldn't run viz_cnmf.show() with a 1200 frames movie. It was possible with a 600 frames movie with fewer much coutours. 

I have dedicated video memory of 16GB.

**Comment by kushalkolar** [comment] 2024-06-28 20:15
Can you please use the template and describe everything.

**Comment by CharlotteWenxin** [comment] 2024-06-29 12:09
I'm sorry I was not clear:

    OS: Windows 11
    mesmerize-core version: '0.4.0'
    caiman version: ''1.11.1'
    Hardware description: 16 GPU, 32GB RAM (15.6GB usable) processor: AMD Ryzen 7 7800X3D 8-Core Processor

The kernel died every time I tried to run viz_cnmf.show() with a 1200 frames cnmf processed movie. But it was possible with a 600 frames movie. I tried increase the dedicated VRAM to 16GB but the kernel still died when I ran viz_cnmf.show ().

Thank you very much for your help!

**Comment by kushalkolar** [comment] 2024-06-29 14:12
What gpu do you have? How many components are you trying to visualize?

**Comment by CharlotteWenxin** [comment] 2024-06-29 14:22
I have integrated GPU and there are about 6000 components.

**Comment by kushalkolar** [comment] 2024-06-29 14:24
You're probably running out of VRAM. Do you expect 6000 components?

**Comment by CharlotteWenxin** [comment] 2024-06-29 15:06
I see. 

No, only about 500, but there are a lot of rejected components along with false positive.

**Comment by kushalkolar** [comment] 2024-06-29 22:50
What does your movie look like, your parameters might be off. You shouldn't
have to curate out thousands of components.

**Comment by CharlotteWenxin** [comment] 2024-07-02 14:52
It looks like this: 
![image](https://github.com/nel-lab/mesmerize-core/assets/157476627/a4ab05b3-d688-446d-9f45-16bcb3583c60)

I applied a mask to exclude the region without neurons and reduce k, then I can use viz_cnmf.show.

**Comment by ethanbb** [comment] 2024-07-11 02:48
@CharlotteWenxin did you get an error message like this in the Jupyter log?

```
thread '<unnamed>' panicked at src/conv.rs:1182:30:
invalid size
stack backtrace:
   0: rust_begin_unwind
```
If so, I think this is due to having contours with 0 points. Will make an issue or PR about it shortly.

**Comment by Agrajag1984** [comment] 2024-09-16 14:18
any development here?

**Comment by CharlotteWenxin** [comment] 2024-09-17 09:22
I didn't get an error and adding a mask helped to reduce the number of false positive.

**Comment by ethanbb** [comment] 2024-09-20 14:53
@Agrajag1984 this issue is fixed in #309, we're waiting for a new caiman release to merge it but you should be able to use this branch for now: https://github.com/proektlab/mesmerize-core/tree/contour-nan-fix

**Comment by kushalkolar** [comment] 2024-09-20 15:20
@Agrajag1984 please post a bug report new issue with all the details.

@ethanbb this appears unrelated to that.

**Closed** 2024-09-20 15:20 UTC

**Comment by ethanbb** [comment] 2024-09-20 15:50
Ah yes I agree it's different from Charlotte's issue, but I believe this is caused by removing nans from empty contours (I got the same error with my data and that was the problem). Anyway we can talk more on a different issue thread.
