### ISSUE TITLE
Rename the output from mescore?

### ISSUE THREAD

**Issue by zhouyi0812** [nel-lab/mesmerize-core#268] opened 2024-01-26 18:08 UTC
Hello!
I wonder if we could rename the output in mescore? for example after motion correction the output file name is xxx motion correction rather than the uuid?
Thank you!

**Comment by kushalkolar** [comment] 2024-01-26 18:32
No, this is by design and there is no reason to do it. What are you trying
to do?

**Comment by zhouyi0812** [comment] 2024-01-26 18:42
Because I have so many movies (1000) that need to segmentation. So I want to do a batch processing.
For example, do motion correction for all first, and then segmentation, then examine the results, so I think if there is a more specific output name, it is easier to manage the file, delete other things and reuse the mmap file?

**Comment by kushalkolar** [comment] 2024-01-26 19:04
You can manage all that with the DataFrame, you can give each item any name you want.

**Comment by zhouyi0812** [comment] 2024-01-26 19:14
Thank you!
Also I wonder if you know why when I do cnmfe algorithm, sometimes the it stops running like shows in the terminal. That the cpu is just not doing work, as this too long time to wait.
Thank you!

![Screenshot 2024-01-26 111046](https://github.com/nel-lab/mesmerize-core/assets/48576330/1b39ae19-58da-4f13-8dd1-cae05c94449b)

![performance](https://github.com/nel-lab/mesmerize-core/assets/48576330/3f8f73dd-8bdb-4965-aff4-77454a2f473d)

**Comment by kushalkolar** [comment] 2024-01-26 20:10
@EricThomson

**Comment by clewis7** [comment] 2024-01-29 14:48
Hi @zhouyi0812,

What Kushal means is that every time you add a movie to your DataFrame to run motion correction or cnmfe, you can specify an `item_name`. This should allow you to more readily organize your movies.

For example:
```
import mesmerize_core as mc 

# set your batch_path
batch_path = "/path/to/where/you/want/to/store/dataframe/batch.pickle"

# create a batch
df = mc.create_batch(batch_path)

# set movie_path
movie_path = "/path/to/movie/movie.tif"

# set mcorr params
mcorr_params1 =\
{
  'main': 
    {
        'max_shifts': [24, 24],
        'strides': [48, 48],
        'overlaps': [24, 24],
        'max_deviation_rigid': 3,
        'border_nan': 'copy',
        'pw_rigid': True,
        'gSig_filt': None
    },
}

# add item with an item name
df.caiman.add_item(
    algo='mcorr',
    item_name = "movie1",
    input_movie_path=movie_path,
    params=mcorr_params1,
)
```

Here I am setting the `item_name` to be `movie1`, but this can be anything you want.

**Comment by kushalkolar** [comment] 2024-02-16 06:01
Closing as this seems to be solved.

**Closed by kushalkolar** 2024-02-16 06:01 UTC
